-- =====================================================================
-- CITIZEN AWARENESS PORTAL - SUPABASE DATABASE SCHEMA AND SEEDING
-- =====================================================================
-- This SQL script creates the necessary tables, enables Row-Level Security (RLS),
-- defines access control policies, and seeds the database with initial fallback data.
-- Paste these queries in your Supabase SQL Editor.
-- =====================================================================

-- Clean up existing tables if they exist (optional, uncomment if resetting)
-- DROP TABLE IF EXISTS public.feedback;
-- DROP TABLE IF EXISTS public.awareness_content;
-- DROP TABLE IF EXISTS public.government_updates;
-- DROP TABLE IF EXISTS public.government_links;
-- DROP TABLE IF EXISTS public.helplines;
-- DROP TABLE IF EXISTS public.faqs;
-- DROP TABLE IF EXISTS public.documents;
-- DROP TABLE IF EXISTS public.schemes;

-- =====================================================================
-- 1. TABLE CREATION
-- =====================================================================

-- Schemes Table
CREATE TABLE IF NOT EXISTS public.schemes (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    audience TEXT NOT NULL,
    description TEXT NOT NULL,
    eligibility TEXT,
    documents TEXT,
    benefits TEXT,
    process TEXT,
    apply_link TEXT DEFAULT '#',
    state TEXT DEFAULT 'All India',
    language TEXT DEFAULT 'en',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Documents Table
CREATE TABLE IF NOT EXISTS public.documents (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    purpose TEXT NOT NULL,
    documents_required TEXT[] DEFAULT '{}',
    process TEXT[] DEFAULT '{}',
    link TEXT DEFAULT '#',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- FAQs Table
CREATE TABLE IF NOT EXISTS public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Helplines Table
CREATE TABLE IF NOT EXISTS public.helplines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    number TEXT NOT NULL,
    category TEXT,
    availability TEXT DEFAULT '24x7',
    link TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Government Links Table
CREATE TABLE IF NOT EXISTS public.government_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Government Updates Table
CREATE TABLE IF NOT EXISTS public.government_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    summary TEXT,
    date DATE NOT NULL,
    link TEXT DEFAULT '#',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Awareness Content (Scams and Alerts) Table
CREATE TABLE IF NOT EXISTS public.awareness_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('scam', 'awareness')),
    title TEXT NOT NULL,
    warning TEXT NOT NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Feedback Table
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT 'Anonymous',
    email TEXT,
    category TEXT DEFAULT 'general',
    message TEXT NOT NULL,
    rating INTEGER,
    language TEXT DEFAULT 'en',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- =====================================================================
-- 2. ROW-LEVEL SECURITY (RLS) POLICIES & PERMISSIONS
-- =====================================================================

-- Enable RLS on all tables
ALTER TABLE public.schemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.helplines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.government_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.government_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.awareness_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Select policies (Allow anyone to read general data)
DROP POLICY IF EXISTS "Allow public read access to schemes" ON public.schemes;
CREATE POLICY "Allow public read access to schemes" ON public.schemes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to documents" ON public.documents;
CREATE POLICY "Allow public read access to documents" ON public.documents FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to faqs" ON public.faqs;
CREATE POLICY "Allow public read access to faqs" ON public.faqs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to helplines" ON public.helplines;
CREATE POLICY "Allow public read access to helplines" ON public.helplines FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to government_links" ON public.government_links;
CREATE POLICY "Allow public read access to government_links" ON public.government_links FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to government_updates" ON public.government_updates;
CREATE POLICY "Allow public read access to government_updates" ON public.government_updates FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to awareness_content" ON public.awareness_content;
CREATE POLICY "Allow public read access to awareness_content" ON public.awareness_content FOR SELECT USING (true);

-- Feedback policies (Allow public to write, but only authenticated dashboard/admin users to read)
DROP POLICY IF EXISTS "Allow public anonymous submissions to feedback" ON public.feedback;
CREATE POLICY "Allow public anonymous submissions to feedback" ON public.feedback FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to read feedback" ON public.feedback;
CREATE POLICY "Allow authenticated users to read feedback" ON public.feedback FOR SELECT TO authenticated USING (true);

-- Grant access permissions to Supabase service roles (anon, authenticated)
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT INSERT ON public.feedback TO anon, authenticated;


-- =====================================================================
-- 3. SEED DATA INSERTION
-- =====================================================================

-- Seeding public.schemes Table from schemes.csv
INSERT INTO public.schemes (id, key, slug, name, category, audience, description, eligibility, documents, benefits, process, apply_link, state, language)
VALUES
('scheme_csv_001', 'pm-kushal-vikas', 'pm-kushal-vikas', 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)', 'Skill Development', 'youth', 'Skill certification scheme aiming to enable a large number of Indian youth to take up industry-relevant skill training.', 'Any unemployed youth or school/college dropouts who are citizens of India.', 'Aadhaar Card, Bank Account Details, Education Certificates, Passport Size Photographs', 'Free skill training, assessment, and certification. Financial rewards upon successful completion and placement assistance.', 'Register online on the PMKVY portal, choose a training center and course, complete training, and appear for the assessment.', 'https://www.pmkvyofficial.org/', 'All India', 'en'),
('scheme_csv_002', 'pm-suraksha-bima', 'pm-suraksha-bima', 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)', 'Insurance', 'public', 'Government-backed accident insurance scheme in India targeting a wide section of the population.', 'All savings bank account holders aged between 18 and 70 years.', 'Aadhaar Card, Bank Account Details, KYC Documents', 'Accidental death and full disability cover of Rs. 2 Lakh; partial disability cover of Rs. 1 Lakh.', 'Submit the application form to your bank or register through internet banking with auto-debit consent.', 'https://www.jansuraksha.gov.in/', 'All India', 'en'),
('scheme_csv_003', 'pm-jeevan-jyoti', 'pm-jeevan-jyoti', 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)', 'Insurance', 'public', 'Government-backed life insurance scheme in India providing annual term life insurance.', 'All savings bank account holders aged between 18 and 50 years.', 'Aadhaar Card, Bank Account Details, Health Declaration Form', 'Life cover of Rs. 2 Lakh in case of death of the insured due to any reason.', 'Fill the PMJJBY enrollment form at your banking branch or apply online via net banking.', 'https://www.jansuraksha.gov.in/', 'All India', 'en'),
('scheme_csv_004', 'stand-up-india', 'stand-up-india', 'Stand-Up India Scheme', 'Business & Entrepreneurship', 'entrepreneurs', 'Scheme promoting entrepreneurship among women and Scheduled Castes or Scheduled Tribes.', 'SC/ST and/or women entrepreneurs above 18 years of age. Loan only for greenfield projects.', 'Identity Proof, Address Proof, Business Plan, Caste Certificate (if applicable), Assets & Liabilities Statement', 'Bank loans between Rs. 10 Lakh and Rs. 1 Crore for setting up a greenfield enterprise.', 'Apply online at Stand-Up India portal, connect with a branch counselor, and submit the loan application form.', 'https://www.standupmitra.in/', 'All India', 'en'),
('scheme_csv_005', 'pm-mudra-yojana', 'pm-mudra-yojana', 'Pradhan Mantri MUDRA Yojana (PMMY)', 'Business & Entrepreneurship', 'entrepreneurs', 'Provides loans up to Rs. 10 Lakh to non-corporate, non-farm small/micro enterprises.', 'Any Indian citizen having a business plan for a non-farm sector income-generating activity.', 'MUDRA Application Form, Identity/Address Proof, Business Identity Proof, 2 Passport Photos', 'Collateral-free loans under three categories: Shishu (up to 50k), Kishor (50k-5L), and Tarun (5L-10L).', 'Approach a commercial bank, RRB, MFI, or cooperative bank, or apply online via Udyami Mitra portal.', 'https://www.mudra.org.in/', 'All India', 'en'),
('scheme_csv_006', 'pm-ujjwala-yojana', 'pm-ujjwala-yojana', 'Pradhan Mantri Ujjwala Yojana (PMUY)', 'Social Welfare', 'women', 'Provides clean cooking fuel (LPG connections) to women from BPL (Below Poverty Line) households.', 'Adult woman belonging to a poor household without an existing LPG connection in the name of any family member.', 'Aadhaar Card, BPL Ration Card, Bank Account Details, Address Proof', 'Free LPG connection with financial support of Rs. 1,600 per connection plus interest-free loan for stove/refill.', 'Submit application form at nearest LPG distributor or apply online through the PMUY website.', 'https://www.pmuy.gov.in/', 'All India', 'en'),
('scheme_csv_007', 'sukanya-samriddhi', 'sukanya-samriddhi', 'Sukanya Samriddhi Yojana (SSY)', 'Women Empowerment', 'parent', 'A small deposit scheme for the girl child, launched under the ''Beti Bachao Beti Padhao'' campaign.', 'Parents or legal guardians of a girl child aged 10 years or below. Maximum 2 accounts per family.', 'Girl Child''s Birth Certificate, Parent''s Identity and Address Proof, Photo', 'High interest rate, tax benefits under Section 80C, and a maturity payout when the girl turns 21.', 'Open account at any post office or authorized commercial bank branches by submitting the form and deposit.', 'https://www.indiapost.gov.in/', 'All India', 'en'),
('scheme_csv_008', 'pm-svanidhi', 'pm-svanidhi', 'PM SVANidhi Scheme', 'Business & Entrepreneurship', 'vendors', 'Special micro-credit facility scheme for providing affordable working capital loans to street vendors.', 'Urban street vendors vending in urban areas on or before March 24, 2020.', 'Aadhaar Card, Voter Card, Street Vendor ID Card or Letter of Recommendation (LoR)', 'Working capital loan up to Rs. 10,000 for 1st tranche, Rs. 20,000 for 2nd tranche, and Rs. 50,000 for 3rd tranche.', 'Apply online through PM SVANidhi Portal, or via a Banking Correspondent (BC)/Common Service Centre (CSC).', 'https://pmsvanidhi.mohua.gov.in/', 'All India', 'en'),
('scheme_csv_009', 'day-nrlm', 'day-nrlm', 'Deendayal Antyodaya Yojana - NRLM', 'Livelihoods', 'rural', 'Organizes rural poor households into Self Help Groups (SHGs) and supports them for livelihoods.', 'At least one member from each rural poor household (preferably a woman) to be brought under SHG network.', 'SHG Member details, Aadhaar Card, Bank Account, Ration Card', 'Revolving fund, community investment fund support, interest subvention on loans, and capacity building.', 'Form a Self Help Group, register with block mission management unit, open bank account, and apply for revolving fund.', 'https://aajeevika.gov.in/', 'All India', 'en'),
('scheme_csv_010', 'janani-suraksha', 'janani-suraksha', 'Janani Suraksha Yojana (JSY)', 'Health & Family Welfare', 'pregnant_women', 'Safe motherhood intervention promoting institutional delivery among poor pregnant women.', 'All pregnant women belonging to BPL/SC/ST households delivering in government or accredited private health facilities.', 'JSY Card, Bank Account Details, Address Proof, BPL Card', 'Cash assistance of Rs. 1,400 in rural areas and Rs. 700 in urban areas to the mother, and incentives to ASHA workers.', 'Register with the local auxiliary nurse midwife (ANM) or ASHA worker, fill JSY form, and deliver at institutional facility.', 'https://nhm.gov.in/', 'All India', 'en'),
('scheme_csv_011', 'pm-vishwakarma', 'pm-vishwakarma', 'PM Vishwakarma Scheme', 'Skill Development', 'artisans', 'Provides end-to-end support to artisans and craftspeople who work with their hands and tools.', 'An artisan or craftsperson working in one of the 18 family-based traditional trades.', 'Aadhaar Card, Mobile Number, Bank Details, Ration Card, Skill Certificate (if any)', 'Biometric registration, PM Vishwakarma Certificate, skill upgrading, toolkit incentive of Rs. 15,000, credit support up to Rs. 3 Lakh.', 'Apply online at CSC or the PM Vishwakarma portal, complete three-step verification, and obtain certificate.', 'https://pmvishwakarma.gov.in/', 'All India', 'en'),
('scheme_csv_012', 'pm-awas-yojana-urban', 'pm-awas-yojana-urban', 'Pradhan Mantri Awas Yojana - Urban (PMAY-U)', 'Housing', 'public', 'Aims to provide all-weather pucca houses to eligible urban households.', 'Beneficiary family should not own a pucca house in their name anywhere in India. Annual income rules apply.', 'Aadhaar Card, Voter Card, Pan Card, Bank Account details, Income Certificate, Land ownership documents', 'Interest subsidy on home loans, financial assistance for house construction/enhancement.', 'Apply online through the PMAY-U portal or submit application via a Common Service Centre (CSC).', 'https://pmaymis.gov.in/', 'All India', 'en'),
('scheme_csv_013', 'pm-awas-yojana-gramin', 'pm-awas-yojana-gramin', 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)', 'Housing', 'rural', 'Aims to provide a pucca house with basic amenities to all houseless households in rural areas.', 'Rural families living in kutcha/dilapidated houses as per SECC database.', 'Aadhaar Card, Bank Account details, Swachh Bharat Mission registration number, Job card number', 'Financial assistance of Rs. 1.2 Lakh in plains and Rs. 1.3 Lakh in hilly/difficult areas for house construction.', 'Beneficiary list generated based on SECC data. Gram Sabha validates list. Local administration contacts beneficiaries.', 'https://pmayg.nic.in/', 'All India', 'en'),
('scheme_csv_014', 'atal-pension-yojana', 'atal-pension-yojana', 'Atal Pension Yojana (APY)', 'Pension', 'public', 'Pension scheme focused on the unorganized sector workers to secure their old age.', 'All citizens of India aged between 18 and 40 years holding a savings bank account.', 'Aadhaar Card, Bank Account Details, Mobile Number', 'Minimum guaranteed monthly pension of Rs. 1,000, 2,000, 3,000, 4,000, or 5,000 after the age of 60.', 'Approach the bank where savings account is held, fill APY registration form, and opt for auto-debit.', 'https://www.npscra.nsdl.co.in/', 'All India', 'en'),
('scheme_csv_015', 'pm-kisan-maan-dhan', 'pm-kisan-maan-dhan', 'PM Kisan Maan-Dhan Yojana', 'Pension', 'farmers', 'Pension scheme to secure the lives of Small and Marginal Farmers in their old age.', 'Small and marginal farmers owning cultivable land up to 2 hectares, aged 18 to 40 years.', 'Aadhaar Card, Bank Account Details, Land Possession Document, KCC Card (optional)', 'Minimum assured pension of Rs. 3,000 per month after attaining the age of 60 years.', 'Apply online at nearest CSC or PM-KMDY portal. Farmers make monthly contribution matched by Central Government.', 'https://maandhan.in/', 'All India', 'en'),
('scheme_csv_016', 'ladli-behna-yojana', 'ladli-behna-yojana', 'Ladli Behna Yojana', 'Women Welfare', 'women', 'State level scheme to support the health and economic independence of women.', 'Women residents of the specific state (e.g., MP) aged 21 to 60 years. Income limitations apply.', 'Samagra ID (if applicable), Aadhaar Card, Bank Account (DBT enabled), Photo', 'Monthly financial aid of Rs. 1,250 transferred directly to the beneficiary''s bank account.', 'Submit applications at ward offices or through local camps, complete e-KYC, and verify registration.', 'https://cmladlibahna.mp.gov.in/', 'Madhya Pradesh', 'en'),
('scheme_csv_017', 'pm-egp', 'pm-egp', 'Prime Minister''s Employment Generation Programme (PMEGP)', 'Employment', 'entrepreneurs', 'Credit-linked subsidy program for generating self-employment opportunities through micro-enterprises.', 'Any individual above 18 years of age. At least VIII standard pass for project costs above 10 Lakh.', 'Aadhaar, Project Report, Education Certificate, Caste/Special Category Certificate, PAN', 'Subsidy of 15% to 35% on project costs up to Rs. 50 Lakh for manufacturing and Rs. 20 Lakh for service sector.', 'Apply online on the KVIC website, upload required documents, bank evaluates project and sanctions loan.', 'https://www.kviconline.gov.in/pmegpeportal/', 'All India', 'en'),
('scheme_csv_018', 'digital-india-internship', 'digital-india-internship', 'Digital India Internship Scheme', 'Education & Career', 'students', 'Provides learning opportunities to students in the area of Electronics and IT policies/projects.', 'B.E/B.Tech/M.E/M.Tech/MCA/M.Sc (IT) students with minimum 60% marks in degree/class XII.', 'College Recommendation Letter, Marksheets, Aadhaar Card, Resume', 'Practical exposure in Ministry of Electronics and IT, monthly stipend of Rs. 10,000, and internship certificate.', 'Apply online during the active application window on MeitY portal and undergo screening interview.', 'https://www.meity.gov.in/', 'All India', 'en'),
('scheme_csv_019', 'national-safai-karamcharis', 'national-safai-karamcharis', 'NSKFDC Loan Schemes', 'Social Welfare', 'safai_karamcharis', 'Financial assistance schemes for socio-economic upliftment of Safai Karamcharis and Scavengers.', 'Safai Karamcharis, manual scavengers, and their dependents. No income limit applies.', 'Identity/Address Proof, Occupation Certificate from local authority, Bank Passbook, Aadhaar', 'Concessional loans at low interest rates (4% to 6%) for starting self-employment ventures.', 'Apply through State Channelising Agencies (SCAs), Regional Rural Banks, or designated nationalized banks.', 'https://nskfdc.nic.in/', 'All India', 'en'),
('scheme_csv_020', 'post-matric-sc-students', 'post-matric-sc-students', 'Post Matric Scholarship for SC Students', 'Education', 'students', 'Financial assistance to Scheduled Caste students studying at post-matriculation or post-secondary stages.', 'SC students whose parents'' annual income does not exceed Rs. 2.5 Lakh.', 'Caste Certificate, Income Certificate, Academic Marksheets, Fee Receipt, Bank Details, Aadhaar', '100% compulsory non-refundable fees and maintenance allowance paid directly to student bank accounts.', 'Register and apply on the National Scholarship Portal or State Scholarship Portal during active dates.', 'https://scholarships.gov.in/', 'All India', 'en')
ON CONFLICT (id) DO UPDATE SET
    key = EXCLUDED.key,
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    audience = EXCLUDED.audience,
    description = EXCLUDED.description,
    eligibility = EXCLUDED.eligibility,
    documents = EXCLUDED.documents,
    benefits = EXCLUDED.benefits,
    process = EXCLUDED.process,
    apply_link = EXCLUDED.apply_link,
    state = EXCLUDED.state,
    language = EXCLUDED.language;

-- Seeding public.documents Table from documents.csv
INSERT INTO public.documents (id, name, purpose, documents_required, process, link)
VALUES
('passport', 'Indian Passport', 'Official travel document for leaving and re-entering India', ARRAY['Proof of Address (Aadhaar/Utility Bill)', 'Proof of Date of Birth (Birth Certificate/10th Marksheet)', 'Photo Identity Proof', 'Non-ECR proof if applicable']::TEXT[], ARRAY['Register on the Passport Seva Online Portal', 'Login and fill the application form online', 'Pay the required fee and schedule an appointment at the nearest PSK', 'Visit the Passport Seva Kendra with original documents', 'Complete the police verification process at your residence', 'Receive passport via speed post after verification']::TEXT[], 'https://www.passportindia.gov.in/'),
('voter_id', 'Voter ID Card (EPIC)', 'Proof of identity and eligibility to vote in elections', ARRAY['Proof of Address', 'Proof of Identity', 'Passport size photograph', 'Declaration Form 6']::TEXT[], ARRAY['Visit the National Voters Service Portal (NVSP)', 'Fill Form 6 online for new voter registration', 'Upload age proof, address proof, and photograph', 'The Booth Level Officer (BLO) will visit your house for verification', 'After approval, the Voter ID card is printed and posted to your address']::TEXT[], 'https://www.nvsp.in/'),
('driving_license', 'Driving License', 'Official document permitting operation of motor vehicles', ARRAY['Learner License', 'Address Proof', 'Age Proof', 'Form 1 and 1A (Medical Certificate if applicable)', 'Fee Payment Receipt']::TEXT[], ARRAY['Apply for a Learner License online on Sarathi Parivahan portal', 'Take the online learner''s test and pass it', 'After 30 days of Learner License, apply for permanent Driving License online', 'Book a slot for a driving test at the local RTO office', 'Appear for the driving test; if you pass, the DL will be dispatched by post']::TEXT[], 'https://sarathi.parivahan.gov.in/'),
('ration_card', 'Ration Card', 'State-issued document for buying subsidized food grains', ARRAY['Aadhaar Cards of all family members', 'Income Proof', 'Residency Proof', 'Passport size photo of head of family']::TEXT[], ARRAY['Visit the state food and civil supplies portal or local FCS office', 'Fill the Application Form for new Ration Card', 'Submit copies of Aadhaar cards and family income proofs', 'FCS inspectors conduct field verification', 'Receive ration card from the local fair price shop or download online']::TEXT[], 'https://nfsa.gov.in/'),
('birth_certificate', 'Birth Certificate', 'Primary proof of birth, date, place, and parentage', ARRAY['Discharge certificate from hospital', 'Aadhaar Card of parents', 'Marriage certificate of parents (optional)', 'Identity proof of informant']::TEXT[], ARRAY['Get a birth registration form from the municipal corporation or Gram Panchayat', 'Register the birth within 21 days at the local registrar office', 'Provide hospital discharge summary and parental identity documents', 'Pay the nominal fee for additional copies of the birth certificate', 'Collect the certificate from the municipal counter or download online']::TEXT[], 'https://crsorgi.gov.in/'),
('caste_certificate', 'Caste Certificate', 'Official proof of belonging to a reserved category (SC/ST/OBC)', ARRAY['Aadhaar Card', 'Proof of residency', 'Father''s caste certificate or community proof', 'Affidavit declaring caste status', 'Income certificate (for OBC non-creamy layer)']::TEXT[], ARRAY['Apply online on the state e-District portal or at a local CSC center', 'Fill the application form and upload scanned copies of proofs', 'Application is forwarded to local Revenue Inspector / Tehsildar', 'Tehsildar verifies the caste history through local inquiry', 'Once approved, download the digitally signed caste certificate']::TEXT[], 'https://www.myscheme.gov.in/'),
('domicile_certificate', 'Domicile Certificate', 'Proof that a person is a resident of a particular State/UT', ARRAY['Aadhaar Card', 'School leaving certificate showing residency', 'Land registry papers or rent agreement', 'Ration card or voter list entry', 'Affidavit in prescribed format']::TEXT[], ARRAY['Login to your state''s e-District website', 'Fill the residency / domicile certificate form', 'Submit proofs showing continuous residency for specified years (usually 5-15 years)', 'Local revenue authority (Patwari/Lekhpal) conducts verification', 'Download the issued Domicile Certificate from the portal']::TEXT[], 'https://www.myscheme.gov.in/'),
('marriage_certificate', 'Marriage Certificate', 'Proof of legal registration of marriage', ARRAY['Application form signed by husband and wife', 'Proof of birth of both parties', 'Address proof before and after marriage', 'Two marriage photographs', 'Wedding invitation card', 'Witness identity proofs (usually 3 witnesses)']::TEXT[], ARRAY['File an application online or at the Sub-Registrar''s Office (SRO) in your area', 'Submit marriage invitation card, photos, and age/address proofs', 'Both partners and witnesses must appear before the Sub-Registrar on the appointed date', 'Under Hindu Marriage Act, certificate is issued in a few days. Under Special Marriage Act, a 30-day notice is posted', 'Collect the marriage certificate signed by the Registrar']::TEXT[], 'https://www.india.gov.in/'),
('disability_certificate', 'Disability Certificate (UDID Card)', 'Official identity card for persons with disabilities to claim benefits', ARRAY['Aadhaar Card', 'Address Proof', 'Recent passport size photograph', 'Medical reports showing disability details']::TEXT[], ARRAY['Register on the Swavlambancard (UDID) portal', 'Fill the personal, address, and disability details in the online form', 'Select the government hospital for physical medical assessment', 'Visit the designated hospital on the scheduled date for medical board checkup', 'Medical board determines disability percentage, and UDID card is issued online and posted']::TEXT[], 'https://www.swavlambancard.gov.in/'),
('death_certificate', 'Death Certificate', 'Official proof of death of an individual', ARRAY['Hospital death summary or post-mortem report', 'Aadhaar Card of the deceased', 'Identity proof of the applicant', 'Cremation/burial receipt']::TEXT[], ARRAY['Report the death to the local registrar within 21 days of occurrence', 'Submit the hospital death report or declaration by local headman', 'Provide identity proofs of the deceased and applicant', 'Verify the entry in the death register of the local body', 'Collect the printed death certificate from municipal or panchayat office']::TEXT[], 'https://crsorgi.gov.in/'),
('minority_certificate', 'Minority Certificate', 'Proof of belonging to a religious/linguistic minority community', ARRAY['Aadhaar Card', 'Self-declaration of community membership', 'School leaving certificate', 'Domicile Certificate', 'Parents'' minority declaration or school record']::TEXT[], ARRAY['Apply through the State Minorities Commission or e-District portal', 'Upload self-declaration of religion/linguistic community', 'Attach address and identity proofs', 'Revenue officer verifies the credentials', 'Obtain the digital certificate from the portal dashboard']::TEXT[], 'https://www.minorityaffairs.gov.in/'),
('senior_citizen_card', 'Senior Citizen Card', 'Grants age concessions for travel, healthcare, and utility bills', ARRAY['Proof of Age (PAN Card/Birth Certificate)', 'Proof of Address', 'Two passport size photographs', 'Medical certificate showing blood group']::TEXT[], ARRAY['Apply through the state Social Welfare Department portal or local municipal office', 'Fill the senior citizen registration form', 'Upload age proof (showing age 60 or above) and photo', 'Verification is done by social welfare officers', 'Collect the Senior Citizen ID Card which lists blood group, emergency contact, and age benefits']::TEXT[], 'https://www.india.gov.in/'),
('pan_card', 'PAN Card', 'Permanent Account Number for all tax-related financial transactions', ARRAY['Aadhaar Card (serves as identity, address, and date of birth proof)', 'Recent passport size photographs (for physical forms)', 'Valid mobile number linked with Aadhaar']::TEXT[], ARRAY['Visit NSDL (Protean) or UTIITSL website', 'Fill Form 49A online for Indian Citizens', 'Choose e-KYC option for instant digital PAN using Aadhaar OTP', 'Pay application fee of around Rs. 107 online', 'Physical PAN card will be delivered to your Aadhaar address, and e-PAN is sent to your email']::TEXT[], 'https://www.onlineservices.nsdl.com/'),
('aadhaar_card', 'Aadhaar Card', '12-digit unique identity number based on biometrics and demographics', ARRAY['Proof of Identity (Passport/Voter ID)', 'Proof of Address (Utility Bill/Bank statement)', 'Proof of Date of Birth (Birth Certificate/Marksheet)']::TEXT[], ARRAY['Locate and book an appointment at the nearest Aadhaar Enrolment Centre', 'Fill the Aadhaar enrolment form at the center', 'Provide biometric data (iris scan, fingerprints) and a photograph', 'Submit copies of identity and address proofs for scanning', 'Receive an acknowledgment slip with EID; track status online and download e-Aadhaar']::TEXT[], 'https://uidai.gov.in/'),
('e_shram_card', 'e-Shram Card', 'National database of unorganized workers to deliver social security benefits', ARRAY['Aadhaar Card', 'Aadhaar linked active mobile number', 'Bank Account details (account number and IFSC code)']::TEXT[], ARRAY['Visit the e-Shram self-registration portal', 'Enter your Aadhaar-linked mobile number and solve captcha', 'Enter Aadhaar details and authenticate using OTP', 'Fill personal, address, qualification, occupation, and bank details', 'Verify the details and download the e-Shram card containing a 12-digit UAN number']::TEXT[], 'https://eshram.gov.in/'),
('udyam_registration', 'Udyam (MSME) Registration', 'Official registration for small, micro, and medium enterprises to claim subsidies', ARRAY['Aadhaar Card of the proprietor/partner/director', 'PAN Card of the organization', 'GSTIN (if applicable)', 'Bank Account number and IFSC code']::TEXT[], ARRAY['Visit the Udyam Registration portal', 'Enter Aadhaar number and name of entrepreneur, validate with OTP', 'Enter PAN card details and validate tax status', 'Provide business name, location, bank details, and investment figures', 'Submit and receive the Udyam Registration Certificate containing QR code instantly']::TEXT[], 'https://udyamregistration.gov.in/'),
('income_certificate', 'Income Certificate', 'Proof of annual income of a family for fee concessions and scholarships', ARRAY['Aadhaar Card', 'Salary slip or Form 16 (for salaried)', 'Affidavit declaring non-salaried income', 'Ration card or electricity bill', 'Land records (for farmers)']::TEXT[], ARRAY['Access the state e-District portal', 'Complete registration and fill the Income Certificate application form', 'Upload income declaration affidavit and supporting address proofs', 'Application undergoes review by the local revenue inspector', 'Download the digital certificate after approval from the Tehsildar']::TEXT[], 'https://www.myscheme.gov.in/'),
('land_possession', 'Land Possession Certificate (LPC)', 'Establishes legal possession over a piece of land', ARRAY['Registered land deed papers', 'Recent land tax payment receipt', 'Aadhaar Card', 'Voter List copy', 'Affidavit declaring land details']::TEXT[], ARRAY['Apply online on the state Land Records (Bhumi) portal or visit Circle Office', 'Fill application form with Khata/Khesra/Plot numbers', 'Submit copies of registered deeds and current revenue tax receipt', 'An Amin (surveyor) is deputed to measure and verify boundary possession', 'Circle Officer approves and issues LPC showing ownership details']::TEXT[], 'https://www.myscheme.gov.in/'),
('ration_card_surrender', 'Ration Card Surrender Certificate', 'Required when moving to another state or changing category', ARRAY['Active Ration Card', 'Aadhaar Card', 'Proof of transfer/relocation', 'Application form for surrender']::TEXT[], ARRAY['Submit application to District Supply Officer (DSO) or apply online', 'Provide active ration card details and reason for surrender', 'FCS department marks the card as inactive and generates surrender slip', 'Use this surrender slip to apply for a fresh ration card in your new location']::TEXT[], 'https://nfsa.gov.in/'),
('non_creamy_layer', 'OBC Non-Creamy Layer Certificate', 'Required to claim reservation benefits in education and government jobs', ARRAY['Community/Caste Certificate', 'Aadhaar Card', 'Parent''s Income Certificates / Form 16 for last 3 years', 'Affidavit declaring assets and income']::TEXT[], ARRAY['Apply through the e-District website or Citizen Service Centre', 'Submit caste proof and parents'' verified income details of the past three fiscal years', 'Revenue inspectors verify that family income is below the creamy layer threshold (currently Rs. 8 Lakh/year)', 'Tehsildar issues the NCL certificate, usually valid for one financial year']::TEXT[], 'https://www.myscheme.gov.in/')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    purpose = EXCLUDED.purpose,
    documents_required = EXCLUDED.documents_required,
    process = EXCLUDED.process,
    link = EXCLUDED.link;

-- Seeding public.faqs Table from faqs.csv
INSERT INTO public.faqs (id, question, answer, category)
VALUES
(11, 'How can I check the status of my Aadhaar card update?', 'You can check your Aadhaar status online by visiting the UIDAI MyAadhaar portal and entering your 14-digit Enrolment ID (EID) along with the date and time from the acknowledgment slip.', 'Aadhaar'),
(12, 'What is the difference between a PAN card and an e-PAN?', 'A physical PAN card is a plastic card sent by post, whereas an e-PAN is a digitally signed PAN card issued in electronic format. Both are equally valid for all financial and tax transactions.', 'PAN'),
(13, 'How do I link my mobile number to my bank account for DBT?', 'Visit your bank branch with your Aadhaar card and passbook, fill out the DBT enablement/Aadhaar seeding form, and submit it. Some banks also allow this via net banking or ATMs.', 'Banking'),
(14, 'What should I do if my debit card is lost or stolen?', 'Immediately call your bank''s customer care helpline to block the card, or block it instantly using your mobile banking application or internet banking portal to prevent unauthorized transactions.', 'Banking'),
(15, 'How do I report a cybercrime or online financial fraud?', 'You can file a complaint online at the National Cyber Crime Reporting Portal (cybercrime.gov.in) or call the national cybercrime helpline number 1930 immediately.', 'Cyber Safety'),
(16, 'Can a student apply for multiple scholarships on the National Scholarship Portal?', 'While you can search and submit applications for multiple scholarships on NSP, you are generally eligible to receive only one scholarship per academic year, depending on the scheme terms.', 'Education'),
(17, 'Is my digital document in DigiLocker legally valid?', 'Yes, documents issued in DigiLocker are legally recognized on par with original physical documents under Rule 9A of the Information Technology (Preservation and Retention of Information by Intermediaries Providing Digital Locker Facilities) Rules, 2016.', 'DigiLocker'),
(18, 'What is PM Kisan e-KYC and is it mandatory?', 'Yes, e-KYC is mandatory for all PM Kisan beneficiaries to receive their financial benefits. You can complete it using OTP on the PM-Kisan portal or through biometrics at a nearby CSC center.', 'Agriculture'),
(19, 'How do I apply for a duplicate Voter ID card if my original is lost?', 'You can apply for a replacement Voter ID online on the Voter Service Portal (voters.eci.gov.in) by filling Form 8 and selecting the replacement category. A nominal fee or process may apply.', 'Voter ID'),
(20, 'What is the maximum income limit for getting an OBC Non-Creamy Layer certificate?', 'Currently, the family income threshold for the OBC Non-Creamy Layer status is Rs. 8 Lakh per annum. This excludes salary and agricultural income in certain cases.', 'Certificates'),
(21, 'How can I register my business under MSME?', 'You can register your enterprise free of cost on the official Udyam Registration portal (udyamregistration.gov.in). You only need your Aadhaar card, PAN, and basic business details.', 'Business'),
(22, 'How do I know if my ration card is active?', 'You can check your ration card status on your state''s Food and Civil Supplies Department portal by entering your Ration Card number, or via the Mera Ration mobile application.', 'Ration'),
(23, 'What is the validity period of an Income Certificate?', 'The validity of an Income Certificate depends on state rules, but it is typically valid for one financial year from its date of issue.', 'Certificates'),
(24, 'What is the KIRAN helpline?', 'KIRAN (1800-599-0019) is a free, 24/7 national helpline launched by the government to provide mental health support, counseling, and crisis management.', 'Helpline'),
(25, 'Who should I contact if a government official demands a bribe?', 'You can report corruption or bribe demands to the State Anti-Corruption Bureau (ACB) or the Vigilance Department. You can also file a complaint with the Central Vigilance Commission (CVC) online.', 'Governance'),
(26, 'How do I apply for a Senior Citizen Card?', 'You can apply through your state''s e-District portal or local social welfare department. You will need proof of age (showing 60+ years), address proof, and photographs.', 'Certificates'),
(27, 'What is the PM SVANidhi scheme?', 'PM SVANidhi is a micro-credit scheme that provides working capital loans of up to Rs. 10,000 (with subsequent higher tranches) to street vendors to restart their businesses.', 'Business'),
(28, 'Can I track my speed post passport delivery online?', 'Yes, once your passport is dispatched, you will receive a tracking number via SMS. You can track its location on the India Post tracking website (indiapost.gov.in).', 'Passport'),
(29, 'How do I update my address on my Driving License?', 'You can apply for a ''Change of Address'' on the Sarathi Parivahan portal. You will need to upload your current DL and valid address proof, pay the fee, and submit.', 'Driving License'),
(30, 'What is an e-Shram card and who is eligible?', 'The e-Shram card is for unorganized workers (like laborers, construction workers, street vendors, domestic help) aged 16-59. It helps them receive social security schemes directly.', 'Social Security')
ON CONFLICT (id) DO UPDATE SET
    question = EXCLUDED.question,
    answer = EXCLUDED.answer,
    category = EXCLUDED.category;

-- Seeding public.helplines Table from helplines.csv
INSERT INTO public.helplines (id, name, number, category, availability, link)
VALUES
(11, 'National Cyber Crime Helpline', '1930', 'Cyber Safety', '24x7', 'https://cybercrime.gov.in/'),
(12, 'Emergency Response Support System (ERSS)', '112', 'Emergency Services', '24x7', 'https://112.gov.in/'),
(13, 'Women Helpline', '1091', 'Women Safety', '24x7', 'https://www.india.gov.in/'),
(14, 'Child Helpline', '1098', 'Child Welfare', '24x7', 'https://www.childlineindia.org.in/'),
(15, 'National Consumer Helpline', '1915', 'Consumer Protection', '24x7', 'https://consumerhelpline.gov.in/'),
(16, 'Kisan Call Centre (Farmer Helpline)', '1800-180-1551', 'Agriculture', '6 AM to 10 PM', 'https://agricoop.nic.in/'),
(17, 'KIRAN Mental Health Helpline', '1800-599-0019', 'Healthcare', '24x7', 'https://socialjustice.gov.in/'),
(18, 'Senior Citizen National Helpline (Elderline)', '14567', 'Senior Citizens', '8 AM to 8 PM', 'https://socialjustice.gov.in/'),
(19, 'National Highway Helpline', '1033', 'Road Safety', '24x7', 'https://nhai.gov.in/'),
(20, 'Railway Inquiry Helpline', '139', 'Travel Services', '24x7', 'https://enquiry.indianrail.gov.in/'),
(21, 'LPG Leakage Emergency Helpline', '1906', 'Emergency Services', '24x7', 'https://www.mylpg.in/'),
(22, 'Disaster Management Helpline', '1078', 'Emergency Services', '24x7', 'https://ndma.gov.in/'),
(23, 'AIDS Helpline (NACO)', '1097', 'Healthcare', '24x7', 'http://naco.gov.in/'),
(24, 'Anti-Ragging Helpline', '1800-180-5522', 'Education', '24x7', 'https://www.antiragging.in/'),
(25, 'National Tourist Helpline', '1363', 'Travel Services', '24x7', 'https://www.tourism.gov.in/'),
(26, 'Central Vigilance Commission (Anti-Corruption)', '1960', 'Governance', 'Office Hours', 'https://cvc.gov.in/'),
(27, 'Income Tax Helpline', '1800-180-1961', 'Financial Services', '8 AM to 10 PM', 'https://www.incometax.gov.in/'),
(28, 'UIDAI Aadhaar Helpline', '1947', 'Identity Services', '24x7', 'https://uidai.gov.in/'),
(29, 'Elections Helpline', '1950', 'Governance', 'Office Hours', 'https://eci.gov.in/'),
(30, 'Blood Bank Helpline', '104', 'Healthcare', '24x7', 'https://www.redcross.org/')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    number = EXCLUDED.number,
    category = EXCLUDED.category,
    availability = EXCLUDED.availability,
    link = EXCLUDED.link;

-- Seeding public.government_links Table from government_links.csv
INSERT INTO public.government_links (id, title, category, url, description)
VALUES
(11, 'National Portal of India', 'General Directory', 'https://www.india.gov.in/', 'The single window access to information and services provided by various Indian government entities.'),
(12, 'myScheme Portal', 'Scheme Discovery', 'https://www.myscheme.gov.in/', 'A platform that helps citizens discover eligible government schemes based on their demographics.'),
(13, 'UIDAI Official Portal', 'Identity Services', 'https://uidai.gov.in/', 'Official website for Aadhaar card enrollment, updates, status checks, and e-download.'),
(14, 'DigiLocker', 'Document Wallet', 'https://www.digilocker.gov.in/', 'A cloud-based platform for issuance and verification of documents & certificates digitally.'),
(15, 'National Scholarship Portal', 'Education', 'https://scholarships.gov.in/', 'One-stop solution for student scholarships from central ministries and state governments.'),
(16, 'PM Kisan Portal', 'Agriculture', 'https://pmkisan.gov.in/', 'Official portal for landholding farmers to check eligibility, register, and check installment status.'),
(17, 'Passport Seva Kendra', 'Travel Services', 'https://www.passportindia.gov.in/', 'Online registration and appointment booking for obtaining or renewing Indian passports.'),
(18, 'Income Tax Department', 'Tax Services', 'https://www.incometax.gov.in/', 'Official e-filing portal for income tax returns, PAN links, and tax calculations.'),
(19, 'National Cyber Crime Reporting Portal', 'Cyber Safety', 'https://cybercrime.gov.in/', 'A portal for citizens to report cybercrimes online, especially crimes targeting women and children.'),
(20, 'UMANG Web Portal', 'Citizen Services', 'https://web.umang.gov.in/', 'Unified Mobile Application for New-age Governance, offering access to 1200+ services.'),
(21, 'Sarathi Parivahan (RTO)', 'Transport Services', 'https://sarathi.parivahan.gov.in/', 'Ministry of Road Transport website for applying for Driving Licenses and Learner Licenses.'),
(22, 'Udyam Registration Portal', 'Business Services', 'https://udyamregistration.gov.in/', 'Official portal for registering micro, small, and medium enterprises (MSMEs) under MSME Ministry.'),
(23, 'National Consumer Helpline', 'Consumer Protection', 'https://consumerhelpline.gov.in/', 'A grievance redressal portal where consumers can file complaints against businesses or services.'),
(24, 'National Career Service', 'Employment Services', 'https://www.ncs.gov.in/', 'A portal matching job-seekers with employers, training institutes, and career counselors.'),
(25, 'e-Shram Portal', 'Social Security', 'https://eshram.gov.in/', 'National database of unorganized workers to facilitate social welfare schemes delivery.'),
(26, 'Startup India', 'Business Services', 'https://www.startupindia.gov.in/', 'A flagship initiative of the Government of India to build a strong ecosystem for nurturing innovation.'),
(27, 'PM MUDRA Yojana Portal', 'Business Loans', 'https://www.mudra.org.in/', 'Official portal describing collateral-free loans up to 10 Lakhs for micro-enterprises.'),
(28, 'Central Vigilance Commission', 'Governance', 'https://cvc.gov.in/', 'An apex government body to address corruption and promote integrity in public administration.'),
(29, 'Voter Service Portal (ECI)', 'Governance', 'https://voters.eci.gov.in/', 'Official portal of the Election Commission of India for voter registration and updates.'),
(30, 'Swachh Bharat Mission Portal', 'Sanitation', 'https://swachhbharatmission.ddws.gov.in/', 'Official portal detailing sanitation, waste management schemes, and household toilet subsidies.')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    url = EXCLUDED.url,
    description = EXCLUDED.description;

-- Seeding public.government_updates Table from government_updates.csv
INSERT INTO public.government_updates (id, title, category, summary, date, link)
VALUES
(11, 'Advisory on Part-time Job Scams', 'Advisory', 'Ministry of Home Affairs warns citizens against online part-time job offers via WhatsApp/Telegram that ask for investments.', '2026-06-01', 'https://cybercrime.gov.in/'),
(12, 'PAN-Aadhaar Linking Deadline Extended', 'Notification', 'The Central Board of Direct Taxes (CBDT) has extended the deadline for linking PAN with Aadhaar card to prevent PAN deactivation.', '2026-06-02', 'https://www.incometax.gov.in/'),
(13, 'Launch of PM Vishwakarma Scheme Portal', 'New Scheme', 'Prime Minister launches the new portal for PM Vishwakarma, allowing traditional artisans to register and claim incentives.', '2026-06-03', 'https://pmvishwakarma.gov.in/'),
(14, 'Alert: Fake Electricity Bill SMS', 'Advisory', 'Power grid companies warn consumers not to click links in messages claiming their electricity will be disconnected.', '2026-06-04', 'https://cybercrime.gov.in/'),
(15, 'NSP Open for Fresh Registrations', 'Scholarships', 'National Scholarship Portal is now open for pre-matric and post-matric applications for the academic year 2026-27.', '2026-06-05', 'https://scholarships.gov.in/'),
(16, 'Mandatory e-KYC for PM Kisan Beneficiaries', 'Notification', 'Department of Agriculture reminds all registered landholders to complete biometric or OTP e-KYC before the next payout.', '2026-06-06', 'https://pmkisan.gov.in/'),
(17, 'New Guidelines for DigiLocker Accounts', 'Notification', 'DigiLocker enhances user security by introducing six-digit PIN and two-factor authentication for government document access.', '2026-06-07', 'https://www.digilocker.gov.in/'),
(18, 'Digital India Internship Applications Open', 'Careers', 'Ministry of Electronics & IT invites applications for the summer batch of Digital India Internship Scheme from tech graduates.', '2026-06-08', 'https://www.meity.gov.in/'),
(19, 'Advisory: Do Not Share OTP for Courier Delivery', 'Advisory', 'Police departments caution citizens against OTP sharing with delivery agents demanding fees for unexpected packages.', '2026-06-09', 'https://cybercrime.gov.in/'),
(20, 'PM Awas Yojana Gramin Direct Benefit Transfer', 'Notification', 'First installment of house building subsidy transferred directly to over 50,000 rural beneficiaries under PMAY-G.', '2026-06-10', 'https://pmayg.nic.in/'),
(21, 'UDID Card Registration Drives in Rural Districts', 'Social Welfare', 'Ministry of Social Justice organizes block-level camps to identify and register specially-abled citizens for UDID cards.', '2026-06-10', 'https://www.swavlambancard.gov.in/'),
(22, 'Udyam MSME Registration Reaches Milestone', 'Announcement', 'Ministry of MSME announces that active Udyam registrations have crossed 2 Crore, enabling small businesses to access credit.', '2026-06-10', 'https://udyamregistration.gov.in/'),
(23, 'Advisory against Fake Government Websites', 'Advisory', 'NIC (National Informatics Centre) publishes a guide on identifying fake websites mimicking official government domains.', '2026-06-10', 'https://www.india.gov.in/'),
(24, 'Unified Highway Helpline 1033 Operational', 'Services', 'NHAI announces nationwide activation of 1033 helpline for emergency support and towing services on national highways.', '2026-06-10', 'https://nhai.gov.in/'),
(25, 'Free Soil Testing Scheme for Farmers', 'Agriculture', 'Krishi Vigyan Kendras organize free soil testing campaigns to help farmers optimize fertilizer application for kharif crops.', '2026-06-10', 'https://pmkisan.gov.in/'),
(26, 'Central Consumer Protection Authority Advisory', 'Advisory', 'CCPA issues guidelines to prevent unfair trade practices and misleading advertisements on e-commerce platforms.', '2026-06-10', 'https://consumerhelpline.gov.in/'),
(27, 'E-Shram Portal Integrates with NCS', 'Notification', 'Workers registered on e-Shram can now search and apply for jobs on the National Career Service portal with one click.', '2026-06-10', 'https://eshram.gov.in/'),
(28, 'Railway Security App Features Upgraded', 'Services', 'Indian Railways upgrades the safety app with direct video-calling to local RPF assistance booths for female passengers.', '2026-06-10', 'https://enquiry.indianrail.gov.in/'),
(29, 'Special Ayushman Card Campaign in Urban Slums', 'Healthcare', 'Municipal corporations launch a 15-day drive to register daily-wage workers for the PM-JAY health insurance scheme.', '2026-06-10', 'https://beneficiary.nha.gov.in/'),
(30, 'Consumer Grievance Redressal Fortnight', 'Announcement', 'National Consumer Helpline organizes a fortnight dedicated to resolving pending service provider complaints.', '2026-06-10', 'https://consumerhelpline.gov.in/')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    summary = EXCLUDED.summary,
    date = EXCLUDED.date,
    link = EXCLUDED.link;

-- Seeding public.awareness_content Table from awareness_content.csv
INSERT INTO public.awareness_content (id, type, title, warning, action)
VALUES
(11, 'scam', 'Electricity Bill Disconnection Scam', 'Receiving text messages warning that electricity will be cut off tonight unless you call a specific mobile number or download an app.', 'Do not call the number. Contact the official electricity board helpline directly or check your bill on the official board website.'),
(12, 'scam', 'Fake Customer Care Toll-Free Numbers', 'Searching for customer care numbers on search engines can lead to fake numbers posted by scammers mimicking banks/airlines.', 'Only use customer care numbers found on official mobile apps, or printed on the back of your credit/debit cards.'),
(13, 'scam', 'Part-Time Job / Telegram Task Scams', 'Promises of earning thousands daily by doing simple tasks like liking videos, followed by demands to join investment groups.', 'Never transfer money to get high-paying simple tasks. Report such groups on the social app and cybercrime portal.'),
(14, 'scam', 'Kaun Banega Crorepari WhatsApp Lottery', 'Receiving audio messages and posters claiming you have won a lottery of Rs. 25 Lakh, requesting processing fees.', 'This is a 100% fake lottery scam. Do not pay any ''processing fee'' or tax, and block the unknown number immediately.'),
(15, 'scam', 'Courier Delivery Fraud (FedEx Scam)', 'Scammers call claiming a parcel sent by you contains illegal substances, demanding payment or bank details to avoid arrest.', 'No law agency or courier service demands online payment over a call to clear cases. Hang up and report immediately to 1930.'),
(16, 'scam', 'Remote Device Access App Scam', 'Scammers ask you to download apps like AnyDesk, TeamViewer, or RustDesk under the pretext of resolving a tech support problem.', 'Downloading these apps gives complete control of your screen and OTPs to the scammer. Never install remote access apps for strangers.'),
(17, 'scam', 'Aadhaar Enabled Payment System (AePS) Fraud', 'Biometric fingerprints copied from property papers or registry documents can be misused to withdraw money via AePS.', 'Lock your biometrics using the UIDAI portal or mAadhaar app. Unlock them temporarily only when you need to authenticate.'),
(18, 'scam', 'Fake Government Subsidy Links', 'Messages on WhatsApp claiming government is distributing free laptops, tablets, or solar panels if you click a link and forward it.', 'Check the URL domain. Government websites always end in .gov.in or .nic.in. Do not forward such unverified viral links.'),
(19, 'scam', 'Urgent UPI Request Scam', 'Scammers send UPI collect requests or QR codes, claiming that scanning the code will deposit money into your account.', 'You NEVER need to enter your UPI PIN or scan a QR code to receive money. Entering your PIN always deducts money from your account.'),
(20, 'scam', 'Sextortion and Video Call Blackmail', 'Receiving video calls from unknown numbers, which are recorded with obscene footage and used to blackmail you for money.', 'Do not pick up video calls from unknown numbers. If trapped, do not pay money. File a complaint immediately with the cyber police.'),
(21, 'awareness', 'Always check Website URLs', 'Scam sites use look-alike domain names such as ''pm-kisan-portal.in'' instead of the official ''pmkisan.gov.in''.', 'Always ensure the website domain ends with ''.gov.in'' or ''.nic.in'' before submitting personal or banking data.'),
(22, 'awareness', 'Protect your OTP and PINs', 'No official, bank clerk, or helpline agent is authorized to ask for your bank OTP, PIN, password, or CVV.', 'Keep OTPs confidential. If anyone asks for it, treat them as a potential scammer and end the communication.'),
(23, 'awareness', 'Secure your Social Media Accounts', 'Compromised social media accounts are used by hackers to send urgent borrowing requests to your friends.', 'Enable Two-Factor Authentication (2FA) on WhatsApp, Facebook, and Instagram to prevent account hijacking.'),
(24, 'awareness', 'Use DigiLocker for Safety', 'Carrying physical certificates can lead to theft, damage, or loss of critical citizenship proofs.', 'Download and sign up on DigiLocker to store and present digital, legally valid copies of driving licenses, marksheets, and Aadhaar.'),
(25, 'awareness', 'Block Spam Calls via Sanchar Saathi', 'Spam calls and fake SIM cards registered in your name can expose you to legal risks.', 'Visit the Sanchar Saathi portal (sancharsaathi.gov.in) to check the number of active SIMs linked to your Aadhaar card.'),
(26, 'awareness', 'Keep Device Software Updated', 'Outdated operating systems and applications have security vulnerabilities that hackers can exploit.', 'Turn on automatic updates on your mobile phones and computers to ensure you have the latest security patches.'),
(27, 'awareness', 'Verify Charity / Donation Appeals', 'Scammers set up fake crowd-funding campaigns and UPI QR codes during disasters to siphon funds.', 'Donate only to recognized national funds (like PM CARES) or certified, verified NGOs after confirming their credentials.'),
(28, 'awareness', 'Avoid Public Wi-Fi for Banking', 'Public open Wi-Fi networks at stations or cafes can be intercepted to capture usernames and passwords.', 'Use your private mobile data connection or a secure VPN when logging into net banking or mobile wallets.'),
(29, 'awareness', 'Report Lost Mobile Phones Immediately', 'Lost phones with active SIMs allow thieves to reset passwords and access bank accounts via OTPs.', 'Contact your telecom provider to block the SIM immediately, and register the lost device on the CEIR portal.'),
(30, 'awareness', 'Educate Family Members on Scams', 'Elderly parents and young teenagers are often the softest targets for online scammers.', 'Discuss common scam tactics at home and teach them never to share card details or make urgent financial decisions under pressure.')
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    title = EXCLUDED.title,
    warning = EXCLUDED.warning,
    action = EXCLUDED.action;

-- Seeding public.feedback Table from feedback.csv
INSERT INTO public.feedback (id, name, email, category, message, rating, language)
VALUES
(11, 'Aarav Mehta', 'aarav.mehta@gmail.com', 'General', 'This portal is extremely helpful! I found all information regarding scholarships easily.', 5, 'en'),
(12, 'Sunita Devi', 'sunita.d@yahoo.com', 'Suggestion', 'Please translate the schemes descriptions into Hindi and regional languages as well.', 4, 'hi'),
(13, 'Rajesh Kumar', 'rajesh.agri@rediffmail.com', 'Bug', 'The PM-Kisan portal link leads to a 404 page. Please check and correct the URL.', 3, 'en'),
(14, 'Priya Sharma', 'priya.sharma99@gmail.com', 'General', 'Very clean user interface. The chatbot feature is excellent and answered all my queries immediately.', 5, 'en'),
(15, 'Vijay Chawla', 'vijay_chawla@outlook.com', 'Suggestion', 'An option to download the scheme application steps as a PDF would be very helpful.', 4, 'en'),
(16, 'Anjali Gupta', 'anjali.g@gmail.com', 'General', 'The scam alert section is really eye-opening. Learned about juice-jacking today.', 5, 'en'),
(17, 'Amit Patel', 'amit.patel@hotmail.com', 'Bug', 'The page load speed is slow when loading the complete helpline list on mobile.', 3, 'en'),
(18, 'Ramesh Naik', 'ramesh.naik@gmail.com', 'General', 'Good job putting all government helplines in one place. Saves a lot of time.', 5, 'en'),
(19, 'Kiran Rao', 'kiran.rao@gmail.com', 'Suggestion', 'Would love to see state-specific schemes for Karnataka added to the portal.', 4, 'en'),
(20, 'Meena Swaminathan', 'meena.s@gmail.com', 'General', 'The site is very easy to navigate even for elderly people like me. Thank you.', 5, 'en'),
(21, 'Vikram Malhotra', 'vikram.m@gmail.com', 'Suggestion', 'Please add a dark mode toggle to the dashboard to make it easier to read at night.', 4, 'en'),
(22, 'Deepika Padukone', 'deepika.p@gmail.com', 'General', 'Great initiative! It helped my domestic helper apply for her e-Shram card.', 5, 'en'),
(23, 'Suresh Prabhu', 'suresh.p@gmail.com', 'Bug', 'The search bar doesn''t filter schemes properly when capital letters are used.', 3, 'en'),
(24, 'Harish Iyer', 'harish.iyer@gmail.com', 'General', 'A very clean and secure site. Highly recommend it to everyone looking for schemes.', 5, 'en'),
(25, 'Nisha Patel', 'nisha.p@gmail.com', 'Suggestion', 'Add an alert system to email subscribers when new schemes are launched.', 4, 'en'),
(26, 'Gopal Sharma', 'gopal.s@gmail.com', 'General', 'The helpline numbers are up to date. Tried the cyber fraud line and it worked.', 5, 'en'),
(27, 'Ramanathan Iyer', 'ram.iyer@gmail.com', 'Bug', 'FAQ dropdown is overlapping with the footer on smaller screen sizes.', 3, 'en'),
(28, 'Sita Ram', 'sita.ram@gmail.com', 'General', 'We need more awareness portals like this. Simple language makes it accessible.', 5, 'hi'),
(29, 'Karan Johar', 'karan.j@gmail.com', 'Suggestion', 'Highlighting top trending schemes on the home page would improve discovery.', 4, 'en'),
(30, 'Lata Mangeshkar', 'lata.m@gmail.com', 'General', 'Wonderful portal. Extremely helpful for rural citizens with poor access to offices.', 5, 'hi')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    category = EXCLUDED.category,
    message = EXCLUDED.message,
    rating = EXCLUDED.rating,
    language = EXCLUDED.language;